mode: chatops
branchName: "issue/${issue.number}-${issue.title,}"
gitSafeReplacementChar: "-"
autoCloseIssue: true
copyIssueDescriptionToPR: true
copyIssueLabelsToPR: true
copyIssueAssigneeToPR: true
copyIssueProjectsToPR: true
copyIssueMilestoneToPR: true
