name: Update release draft
on:
  push:
    branches:
      - develop

concurrency:
  group: update-release-draft-${{ github.ref }}

jobs:
  update_release_draft:
    runs-on: ubuntu-latest
    steps:
      # Drafts your next Release notes
      - uses: release-drafter/release-drafter@v5
        with:
          disable-releaser: ${{ github.ref != 'refs/heads/develop' }}
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
